app/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("accounts/", include("django.contrib.auth.urls")),
        path("", include("notes.urls", namespace="notes")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

app/notes/urls.py
from django.urls import path

from notes.views import NoteCreateView, NoteDeleteView, NoteListView, NoteUpdateView


app_name = "notes"
urlpatterns = [
    path("notes/add/", NoteCreateView.as_view(), name="add"),
    path("notes/<int:pk>/", NoteUpdateView.as_view(), name="update"),
    path("notes/<int:pk>/delete/", NoteDeleteView.as_view(), name="delete"),
    path("", NoteListView.as_view(), name="list"),
]

app/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from accounts.managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("Email address"), unique=True)
    is_staff = models.BooleanField(default=False)
    # New users are inactive
    # They needs to be activated by platform Admin
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

app/notes/models.py
from django.db import models

from accounts.models import CustomUser


class Note(models.Model):
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = models.TextField()

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("notes:update", kwargs={"pk": self.pk})

app/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ("email",)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("email",)

app/notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from notes.models import Note


class NoteCreateView(LoginRequiredMixin, CreateView):
    model = Note
    fields = ["title", "text"]
    template_name = "notes/notes_detail.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class NoteUpdateView(LoginRequiredMixin, UpdateView):
    model = Note
    fields = ["text"]
    template_name = "notes/notes_detail.html"


class NoteDeleteView(LoginRequiredMixin, DeleteView):
    model = Note
    success_url = reverse_lazy("notes:list")


class NoteListView(LoginRequiredMixin, ListView):
    model = Note

    paginate_by = 3
    template_name = "notes/notes_list.html"

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(created_by=self.request.user)

app/templates/app.html
{% extends "base.html" %}
{% load static %}
{% block body_styles %}grid sm:flex{% endblock %}
{% block content %}
  <main>
    <nav class="nav">
      <div class="nav-left">
        <a class="brand" href="/">No Frontend App</a>
        <span>{% block page_title %}{% endblock %}</span>
      </div>
      <div class="nav-right">
        <p class="user"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M10.5 5a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0zm.061 3.073a4 4 0 10-5.123 0 6.004 6.004 0 00-3.431 5.142.75.75 0 001.498.07 4.5 4.5 0 018.99 0 .75.75 0 101.498-.07 6.005 6.005 0 00-3.432-5.142z"></path></svg> {{ user.email }}</p>
        {% if request.user.is_superuser %}<a class="button outline" href="{% url 'admin:index' %}">admin</a>{% endif %}
        <a class="button" href="{% url 'logout' %}">logout</a>
      </div>
    </nav>
    <hr>
    <div>
      {% block page_content %}{% endblock %}
    </div>
  </main>
{% endblock content %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TG-Hug: {% block seo_page_title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendor/unpoly.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendor/chota.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/vendor/unpoly.min.js' %}"></script>
  </head>
  <body class="container">
    {% block content %}{% endblock content %}
  </body>
</html>

app/templates/notes/note_confirm_delete.html
{% extends "app.html" %}

{% block page_content %}
<a href="{% url 'notes:list' %}"><<< Back to list</a>
<form method="post" class="confirm" action="{% url 'notes:delete' object.pk %}">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object.title }}"?</p>
  <input class="button error" type="submit" value="Confirm">
</form>
{% endblock %}

app/templates/notes/notes_detail.html
{% extends "app.html" %}

{% block page_content %}
<a href="{% url 'notes:list' %}"><<< Back to list</a>
{% if object.title %}
<h2>{{ object.title }} (Editing)</h2>
{% else %}
<h2>New Note</h2>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  {{ form }}
  <input class="button primary" type="submit" value="Save">
</form>
{% endblock %}

app/templates/notes/notes_list.html
{% extends "app.html" %}

{% block page_content %}
<h1 class="is-center">My Awesome Notes</h1>
<div class="notes">
  {% for note in page_obj %}
  <div class="card">
    <header><h3>{{ note.title }}</h3></header>
    <p>{{ note.text|truncatechars:50 }}</p>
    <footer class="is-right">
      <a class="button outline primary text-primary" href="{% url 'notes:update' note.pk %}">Edit</a>
      <a class="button error" href="{% url 'notes:delete' note.pk %}" up-layer="new" up-target=".confirm" up-size="small">Remove</a>
    </footer>
  </div>
  {% empty %}
    <p class="is-center">No notes exists...</p>
  {% endfor %}
</div>

<p class="is-center">
  <a class="button primary" href="{% url 'notes:add' %}">Add new Note</a>
</p>

<div class="pagination is-center">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
    {% endif %}
  </span>
</div>
{% endblock %}